apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: pipeschlange
spec:
  params:
    - name: massage
  tasks:
    - name: hallo
      taskRef:
        name: ekko
      params:
        - name: massage
          value: "$(params.massage)"
          
